"""initial schema

Revision ID: 42f8f051926f
Revises: 
Create Date: 2026-07-23 23:23:55.964985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f8f051926f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('algo', sa.String(length=32), nullable=False),
    sa.Column('k', sa.Integer(), nullable=False),
    sa.Column('silhouette', sa.Float(), nullable=True),
    sa.Column('mean_ari', sa.Float(), nullable=True),
    sa.Column('n_transactions', sa.Integer(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('scaler_blob', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('txn_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('txn_kind', sa.String(length=16), nullable=False),
    sa.Column('counterparty_raw', sa.Text(), nullable=False),
    sa.Column('counterparty_normalized', sa.Text(), nullable=False),
    sa.Column('reference_hash', sa.String(length=64), nullable=True),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.Column('source_app', sa.String(length=32), nullable=False),
    sa.Column('parse_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_counterparty_normalized'), ['counterparty_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_dedup_key'), ['dedup_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_txn_date'), ['txn_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_txn_kind'), ['txn_kind'], unique=False)

    op.create_table('unparsed_rows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('raw_line', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('cluster_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('centroid_summary', sa.JSON(), nullable=False),
    sa.Column('n_transactions', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clusters_run_id'), ['run_id'], unique=False)

    op.create_table('features',
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('log_amount', sa.Float(), nullable=False),
    sa.Column('dow_sin', sa.Float(), nullable=False),
    sa.Column('dow_cos', sa.Float(), nullable=False),
    sa.Column('day_of_month_norm', sa.Float(), nullable=False),
    sa.Column('merchant_frequency', sa.Float(), nullable=False),
    sa.Column('recency_days', sa.Float(), nullable=False),
    sa.Column('is_recurring', sa.Float(), nullable=False),
    sa.Column('amount_stability', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('insights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=True),
    sa.Column('period_month', sa.String(length=7), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('impact_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insights_run_id'), ['run_id'], unique=False)

    op.create_table('cluster_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('distance_to_centroid', sa.Float(), nullable=False),
    sa.Column('pca_x', sa.Float(), nullable=False),
    sa.Column('pca_y', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Integer(), nullable=False),
    sa.Column('anomaly_reason', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cluster_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cluster_assignments_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cluster_assignments_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cluster_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cluster_assignments_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_cluster_assignments_run_id'))

    op.drop_table('cluster_assignments')
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insights_run_id'))

    op.drop_table('insights')
    op.drop_table('features')
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clusters_run_id'))

    op.drop_table('clusters')
    op.drop_table('unparsed_rows')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_txn_kind'))
        batch_op.drop_index(batch_op.f('ix_transactions_txn_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_dedup_key'))
        batch_op.drop_index(batch_op.f('ix_transactions_counterparty_normalized'))

    op.drop_table('transactions')
    op.drop_table('runs')
    # ### end Alembic commands ###
